# Generated by Django 5.0.2 on 2024-04-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('salary', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('deadline_date', models.DateField()),
            ],
        ),
    ]
