# Generated by Django 4.2.2 on 2024-04-25 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.education')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workexperience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.workexperience')),
            ],
        ),
    ]
