# Generated by Django 4.2.2 on 2024-04-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_appliedjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='education',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='workexperience',
        ),
    ]
