# Generated by Django 5.0.3 on 2024-04-26 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_jobopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.jobopening'),
        ),
    ]
