# Generated by Django 5.0.3 on 2024-04-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_appliedjob_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='max_intake',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
