# Generated by Django 5.0.3 on 2024-04-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_jobopening_max_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='social',
            field=models.TextField(null=True),
        ),
    ]
