# Generated by Django 5.0.3 on 2024-04-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterResume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('type', models.TextField()),
            ],
        ),
    ]
